### ISSUE TITLE
Install steps for Catalina 10.15

### ISSUE THREAD

**Issue by seasaltseasalt** [janbaykara/ebook-scraper#4]
Hi, what would be the steps to install this chrome extension on Catalina OS X 10.15?
I usually use Firefox so I do not know what to do in chrome.firefox extensions are 1-click installations. Thankyou

**Comment by helphelpplease** [comment]
Followed instructions written on the boiler template, Chrome extension foundation

**Comment by helphelpplease** [comment]
So far:
1 created directory where I want to store the extension
2 downloaded the zip file, and unzipped into the above directory
3 in terminal, ran 
npm i
then
npm run build 

Opened Chrome, Navigate to Extensions, turn Developer Mode slider to on
Selected Loaded unpack Extension, and point to the DIST folder in the directory above

**Comment by helphelpplease** [comment]
Using the foundation as a guide

So far:
1 created directory where I want to store the extension
2 downloaded the zip file, and unzipped into the above directory
3 in terminal, ran 
npm i
then
npm run build 

Opened Chrome, Navigate to Extensions, turn Developer Mode slider to on
Selected Loaded unpack Extension, and point to the DIST folder in the directory above

**Comment by helphelpplease** [comment]
Using the foundation as a guide

So far:
1 created directory where I want to store the extension
2 downloaded the zip file, and unzipped into the above directory
3 in terminal, ran 
npm i
then
npm run build 

Opened Chrome, Navigate to Extensions, turn Developer Mode slider to on
Selected Loaded unpack Extension, and point to the DIST folder in the directory above

**Comment by janbaykara** [comment]
See also: #21
