### ISSUE TITLE
Extension is Not grabbing entire chapters [ebookcentral]

### ISSUE THREAD

**Issue by helphelpplease** [janbaykara/ebook-scraper#5]
Perhaps I do not understand how this extension is suppose to work.

I am viewing a title, in online preview, in ebookcental, (using Chrome) and full page count of title is 1621
and if I select a chapter, the extension is only showing 4 pages. The chapter has many more pages.

I do not know where to look to fix or what is best to share for help.

Can you please advise.Thankyou

**Comment by seasaltseasalt** [comment]
Extension grabs online pages viewed online.
To grab entire chapter, page thru the chapter online, then all pages will be grabbed

**Comment by helphelpplease** [comment]
click thru all the pages, and the PDF is built.
